---
- hosts: "10.1.0.30"
  become: true
  vars_files:
    - s4hana_vars.yml
  roles:
    - disk-setup
    - nfs-export
    - swpm-download
    - export-download
    - kernel-download
    - hdbclient-download
    - commonfiles-download
    - ascs-install
    - dbload-install
    - ci-install
